# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d60d3b3d892dadb2bd94e1b560f4e900f8f08640d1d6e34945df8d87661fe209cdf772ecdf59e88af3421810e6de4f9d1585d17f3e07899ba88a13028c3a94a6

test:
  secret_key_base: 58e424ea0d6e9925963e9b82a2dd019f680c908fb39ba76ba6db1cf45084cf5979cba644925b30598bdf8c746ead3d7c31dbd5c9a16f1aa47112bb2e355d7de7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
